name: Build and Release

on:
  push:
    tags:
      - 'v*' # 当你推送 v0.1.0 这样的标签时触发
  workflow_dispatch: # 支持手动触发编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl # 使用 musl 实现静态链接，无需依赖服务器库版本

      - name: Install musl-tools
        run: sudo apt-get install -y musl-tools

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Binary
        # 使用 --release 编译，并针对静态链接优化
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stream_hub-linux-amd64
          path: target/x86_64-unknown-linux-musl/release/stream_hub

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: stream_hub-linux-amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: stream_hub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}